#!/usr/bin/env bash
#Redirection

apt-get -y update
apt-get -y install nginx
echo "server {
       listen 80;
       listen [::]:80;

       root /var/www/html;
       index index.html;

       location /redirect_me {
               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
       }
}" > /etc/nginx/sites-available/default
service nginx restart
