#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update
apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
echo "server {
       listen 80;
       listen [::]:80;

       root /var/www/html;
       index index.html;

       location /redirect_me {
               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
       }
       location /xyz {
               return 404;
       }
       location /xyzfoo {
               return "Ceci n'est pas une page;
       }
}" > /etc/nginx/sites-available/default
service nginx restart
