#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sed -i "/server {/a location /xyz { return 404 \"Ceci n\'est pas une page\"; }" /etc/nginx/sites-available/default
sed -i "/server {/a location /xyzfoo { add_header Contet-Type text/plain; return 200 \"Ceci n\'est pas une page\\\n\\\n\"; }" /etc/nginx/sites-available/default
service nginx restart
