#!/usr/bin/env bash
# Installing and configuring HAproxy on your lb-01 server.
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.6 -y
apt-get install haproxy=2.6.\* -y
cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
echo -e "\nfrontend alx-front\n\tbind *:80\n\tmode http\n\tdefault_backend alx-back\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend alx-back\n\tbalance roundrobin\n\tserver 520004-web-01 54.175.19.58:80 check\n\tserver 520004-web-02 100.25.215.254:80 check\n" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy restart
