#!/usr/bin/env bash
#Fixes nginx for port 8080 to work
# fixed
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
